name: vUnstable
version: '${version}'
main: com.vprolabs.vunstable.vUnstable
api-version: '1.21'
folia-supported: true
load: STARTUP
softdepend: [vAPI]
author: vProLabs
website: https://vprolabs.xyz

commands:
  vunstable:
    description: vUnstable main command
    usage: /vu <give|update|status|reload>
    aliases: [vu]
    permission: vunstable.use
    permission-message: "&cYou don't have permission!"
  rod:
    description: Alias for vunstable
    usage: /vu <give|update|status|reload>
    permission: vunstable.use

permissions:
  vunstable.give:
    description: Allows giving rods to self
    default: op
  vunstable.give.others:
    description: Allows giving rods to other players
    default: op
  vunstable.reload:
    description: Allows reloading config
    default: op
  vunstable.admin:
    description: Allows viewing optimization status and receiving error notifications on join
    default: op
